### ISSUE TITLE
`require': cannot load such file -- pry (LoadError)

### ISSUE THREAD

**Issue by jeremy04** [LaunchPadLab/decanter#60]
Hi I tried installing your gem, but got the following message when running "rails console" or "rails generate".

    /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- pry (LoadError)
	from /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/decanter-1.1.4/lib/decanter/core.rb:1:in `<top (required)>'
	from /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /Users/jeremy/.rbenv/versions/2.3.0/gemsets/react_horse2/gems/decanter-1.1.4/lib/decanter.rb:60:in `<top (required)>'

It was due to my environment not having 'pry' or 'pry-rails' in my Gemfile. 
Adding gem 'pry', fixed the issue. 

You could alternatively fix it in the gem, in core.rb:

    begin
      require 'pry'
    rescue LoadError
      # Gem loads as it should
    end

or by making it  'add_dependency' instead of 'add_development_dependency' in gemspec since it's being required explicitly (in order to use it you have to). Pry is a default in Rails, so really this up to you.

**Comment by francirp** [comment]
Thanks for submitting this issue @jeremy04! We’ll take a look at this today. We don’t want to have a dependency on Pry - we will likely remove that line.
